### ISSUE TITLE
Leaderboard:Epic

### ISSUE THREAD

**Issue by BlueDragn** [chingu-voyages/v44-tier1-team-02#15]
**__Feature Description__** :pushpin:

Leaderboard showing the number of games the current player has won and lost <br>
**__Major User Stories/tasks__** :arrow_double_down:

-  [ ] User can see the display of the total number of wins and losses for each :arrow_backward:
- [ ]  User can see the tally of wins for each of the three ways the game can end :arrow_backward:
- [ ] User can see the tally of losses for each of the three ways the game can end :arrow_backward:
