### ISSUE TITLE
Grid:Epic

### ISSUE THREAD

**Issue by BlueDragn** [chingu-voyages/v44-tier1-team-02#17]
**__Feature Description__**
Make a Grid play ground where game will be played :football:
**__Major User Stories/tasks__**
-   [ ] When the dice are rolled the user will be able to click on squares
    to mark their array.
   -   [ ] When a square is clicked it's color will change from the color used
    for unoccupied squares to the color designation for occupied squares.
   -   [ ] If the total number of squares marked on the grid don't match the
    numbers on the dice an error message must be issued and the user should be
    given the option to re-mark the grid to match the dice.

**Comment by Gayle-Cindy** [comment]
I will work on this user story

**Comment by Gayle-Cindy** [comment]
I will work on this user story
