### ISSUE TITLE
Step 2: 🧑‍🤝‍🧑 Conduct Kickoff meeting

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v44-tier1-team-02#5]
**__Task Description__**
- [x] Using everyone's availability posted to [When2Meet](https://www.when2meet.com/) schedule a Kickoff meeting
- [x] Use the [Kickoff meeting template](https://docs.google.com/document/d/1ozP5lLj_R0kqCWdXEpFDR6sIlP9miXp74DFKZlJyktE/edit?usp=sharing) in the shared document directory we've provided to guide the discussion and to record notes, decisions, and assignments
- [x] Set a time for your next meeting for later in the week

**__Technical Considerations__**
N/a

**__Additional Considerations__**
N/a

**__Resources__**
[Conduct Kickoff Meeting (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#90602edc9c99420ca042039d79ed1173)

**Member of Epic:** #16

**Comment by Ahmed3445** [comment]
good meeting guys.

**Comment by BlueDragn** [comment]
Great meeting you all

**Comment by BlueDragn** [comment]
## Kick off meeting summary
The meeting began with a round of introductions, after which the team delved into a discussion of the project. During this discussion, each member shared their ideas and thoughts, resulting in a healthy exchange of insights. Ahmed provided a presentation on agile methodology, while Anshuman talked about the git workflow. The team is looking forward to their next meeting and continuing to build on the progress made during this one. All in all, it was a productive and valuable meeting.

**Comment by Gayle-Cindy** [comment]
It was Great meeting you all.

**Comment by 00awaudby** [comment]
Was great can't wait to get stuck Into seeing what we build together
